spring:
  application:
    name: exerciseSpringBoot

  # DATABASE
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:C:/Users/user/ToyProject.zip/exerciseSpringBoot/src/main/dbData/local
    driverClassName: org.h2.Driver
    username: sa
    password: pk2258

  # JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    # Uncomment the following lines if needed
    # show-sql: true
    # format-sql: true

  # ENCODING
  web:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
